import { readFile, writeFile } from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const theme=(await readFile(new URL('src/theme.js',root),'utf8')).replace(/^\/\/ ==UserScript==[\s\S]*?\/\/ ==\/UserScript==\s*/, '');
const core=(await readFile(new URL('src/contest-core.mjs',root),'utf8')).replace(/^export /gm,'');
const ui=await readFile(new URL('src/contest-board.js',root),'utf8');
const contestTheme=await readFile(new URL('src/contest-theme.js',root),'utf8');
const markdownCore=(await readFile(new URL('src/markdown-core.mjs',root),'utf8')).replace(/^export /gm,'');
const markdownEditor=await readFile(new URL('src/markdown-editor.js',root),'utf8');
const batchCore=(await readFile(new URL('src/batch-core.mjs',root),'utf8')).replace(/^export /gm,'');
const batchUpload=await readFile(new URL('src/batch-upload.js',root),'utf8');
const backNavigation=await readFile(new URL('src/back-navigation.js',root),'utf8');
const testdataCore=(await readFile(new URL('src/testdata-core.mjs',root),'utf8')).replace(/^export /gm,'');
const testdataGuard=await readFile(new URL('src/testdata-guard.js',root),'utf8');
const classCore=(await readFile(new URL('src/class-core.mjs',root),'utf8')).replace(/^export /gm,'');
const classXlsx=(await readFile(new URL('src/class-xlsx.mjs',root),'utf8')).replace(/^export /gm,'');
const classManager=await readFile(new URL('src/class-manager.js',root),'utf8');
const upsolveCore=(await readFile(new URL('src/upsolve-core.mjs',root),'utf8')).replace(/^export /gm,'');
const upsolveReader=await readFile(new URL('src/upsolve-reader.js',root),'utf8');
const reviewCore=(await readFile(new URL('src/ai-review-core.mjs',root),'utf8')).replace(/^export /gm,'');
const reviewUi=await readFile(new URL('src/ai-review.js',root),'utf8');
const header=`// ==UserScript==
// @name         Accoding Modern · 北航 OJ 管理界面
// @namespace    local.accoding.modern
// @version      1.9.0
// @description  界面美化、班级名册、页内代码复核、独立补题排行榜与提交查看、赛事统计看板、Markdown 兼容编辑与批量测试点选择，保留原站登录和操作。
// @include      https://accoding.buaa.edu.cn:4000/*
// @run-at       document-end
// @grant        none
// @homepageURL  https://github.com/y38501148-max/accoding-modern
// @downloadURL  https://raw.githubusercontent.com/y38501148-max/accoding-modern/main/accoding-modern.user.js
// @updateURL    https://raw.githubusercontent.com/y38501148-max/accoding-modern/main/accoding-modern.user.js
// ==/UserScript==
// Generated by scripts/build.mjs. Edit src/ files, then run npm run build.

`;
await writeFile(new URL('accoding-modern.user.js',root),header+`(() => {\n'use strict';\nif (location.origin !== 'https://accoding.buaa.edu.cn:4000') return;\n${core}\n${ui}\nmountContestBoard(createContestCore());\n${contestTheme}\n${theme}\n${markdownCore}\n${markdownEditor}\nmountMarkdownEditor(createMarkdownCore());\n${batchCore}\n${batchUpload}\nmountBatchUpload(createBatchCore());\n${backNavigation}\nmountBackNavigation();\n${testdataCore}\n${testdataGuard}\nmountTestdataGuard(createTestdataCore());\n${classCore}\n${classXlsx}\n${reviewCore}\n${reviewUi}\n${classManager}\n${upsolveCore}\n${upsolveReader}\nmountClassManager(createClassCore(),createContestCore(),createUpsolveCore(),createUpsolveReader(createContestCore().time),createAiReviewCore());\nmountSubmissionReview(createAiReviewCore());\n})();\n`);
